### ISSUE TITLE
Wrong bottom position of tableViews with translucent NavBar

### ISSUE THREAD

**Issue by bigluck** [maxep/MXSegmentedPager#55] opened 2015-12-14 19:00 UTC
Hi @maxep, sorry for the massive number of issues I'm opening in those days :(

I'm having a rendering problem when using `MXSegmentedPager` without the parallax header and with an `Translucent` `Navigation Bar`.

You can reprocude the same bug using the `MXSegmentedPager-Swift` sample.
- Ad an `Navigation Controller` in the `Main.storyboard`
- Make the `Navigation Controller` as the `Initial View Controller`
- Connect the `MXViewController` as the `root view controller` of the `Navigation Controller`.
  0 In the `Navigation Controller` select the `Navigation Bar` component and enable `Translucent` from the `Attributes inspector`

Last step: comment out all `parallaxHeader` settings from the `MXViewController.swift` file and run.

The last two rows (Row 48 and Row 49) is partially hidden on the bottom of the view

**Comment by maxep** [comment] 2015-12-21 21:42
Hi @bigluck 

Actually, The issue is not that the last rows are hidden, by checking `translucent` the segmented pager should appear under the navigation bar.

**Comment by maxep** [comment] 2015-12-21 22:37
If you want to fix the issue you're describing, you can uncheck Under Top Bars from the MXSegmentedPagerController or add `self.edgesForExtendedLayout = UIRectEdge.None` to the `viewDidLoad`.

**Comment by maxep** [comment] 2016-01-04 14:01
Fixed in 3.0.4

**Closed as completed by maxep** 2016-01-04 14:01 UTC
Labels: bug
