### ISSUE TITLE
SegmentedControl needs layout constraints

### ISSUE THREAD

**Issue by inPhilly** [maxep/MXSegmentedPager#18] opened 2015-05-28 05:49 UTC
I got this working last time by adding the views programmatically (not hooking up MXSegmentedPager in the storyboard). I have some pretty complex view controllers in my app, and I am trying to hook up MXSegmentedPager to an outlet in storyboard, where the top and bottom constraints change.

I have found that the segmented control needs constraints. I added this to - (HMSegmentedControl *)segmentedControl method:

```
    _segmentedControl.translatesAutoresizingMaskIntoConstraints = NO;
    NSDictionary *binding  = @{@"v" : _segmentedControl};
    [self addConstraints:[NSLayoutConstraint
                          constraintsWithVisualFormat:@"H:|-0-[v]-0-|"
                          options:NSLayoutFormatDirectionLeadingToTrailing
                          metrics:nil
                          views:binding]];

    [self addConstraints:[NSLayoutConstraint
                          constraintsWithVisualFormat:@"V:|-0-[v(50)]"
                          options:NSLayoutFormatDirectionLeadingToTrailing
                          metrics:nil
                          views:binding]];
```

which works well. But only in the case that there is no ParallaxHeader.

I am having trouble adding the constraints to the MXSegmentedPager+ParallaxHeader.m file, when a parallax header exists. No matter where I add them, things blow up.

**Comment by maxep** [comment] 2015-05-28 12:24
Hi @mommyme !
This does not work with the parallax category because the segmented control and the pager are added to a scroll view so your constraints will mess up with the parallax layout. Could you provide a example that show your issue, you can modify the example project with a complex controller and constraints and send it to my email. Or maybe add a gif that show what happens.
Because I also use the MXSegmentedPager with constraints in a storyboard and I don't have any issues...

**Comment by inPhilly** [comment] 2015-05-28 21:30
Hi @maxime! I will try to provide an example when I can, but my use case is pretty complex. My issue happens when setting the cover to nil; you currently only set constraints for the parallax header/scrollview, but you do not set constraints when it is not used, and this actually does affect things. I think that when there is no parallax header (cover is nil) constraints should be set on the segmented control and pager. I will try to post an example when I can, but I _think_ this needs to be done.

```
 On Thursday, May 28, 2015 8:24 AM, Maxime <notifications@github.com> wrote:
```

 Hi @mommyme !
This does not work with the parallax category because the segmented control and the pager are added to a scroll view so your constraints will mess up with the parallax layout. Could you provide a example that show your issue, you can modify the example project with a complex controller and constraints and send it to my email. Or maybe add a gif that show what happens.
Because I also use the MXSegmentedPager with constraints in a storyboard and I don't have any issues...—

**Comment by maxep** [comment] 2015-06-01 16:11
Hi @mommyme !

FYI, I'm working on a pure autolayout approach. To do so, the standard class and the parallax category have been merge. I still got a lot of work to do but you can see the code on the [parallax-header-merge](https://github.com/maxep/MXSegmentedPager/tree/parallax-header-merge) branch.

Regards,

Maxime

**Comment by inPhilly** [comment] 2015-06-11 05:44
Hi Maxime. How is the parallax-header-merge branch coming? I was working on some other things and I thought I would come back to this if it was ready.

**Comment by maxep** [comment] 2015-06-11 08:41
Hi @mommyme 

I have still some issues, mainly with ios 7. But you can try it :

```
pod 'MXSegmentedPager', :git => 'https://github.com/maxep/MXSegmentedPager.git', :branch => 'parallax-header-merge'
```

**Comment by inPhilly** [comment] 2015-06-12 23:14
It's a completely different control. I don't know when I will have time to completely rework my project.

**Comment by inPhilly** [comment] 2015-06-13 00:02
I tried it and it still doesn't work with Storyboard. I think that is part of why there are so many issues with the control. Just as you would hook up a UITableView in a storyboard, try to put the MXSegmentedPager in a storyboard. It simply fails every time. I appreciate your hard work on this control, but I think until you test it in storyboard it will have issues. Not all people will need to use it in storyboard, but some people will.

**Comment by maxep** [comment] 2015-06-13 10:22
Hi @mommyme ,

The branch is not completely different, the interface and the category have only been merge. You just have to remove the '+ParallaxHeader.h' from your include, it is not a completely rework.
Well, I used it in storyboard with no issue. Since I can't reproduce your issue and you never provide any sample project, or at least a screenshot, I will close this issue.

Regards, 

Maxime

**Closed as completed by maxep** 2015-06-13 10:22 UTC
Labels: invalid

**Comment by inPhilly** [comment] 2015-06-19 05:41
Sorry, I was having a rough time getting things set with my last comment. I have everything up and running now. Thanks again for this control.
