### ISSUE TITLE
Issue using storyboard

### ISSUE THREAD

**Issue by florentdouine** [maxep/MXSegmentedPager#7] opened 2015-05-13 15:09 UTC
Hi,

i'm trying to add your very nice library into my project but i've got an issue when i insert the mxsegmentedPager directly in the storyboard.
It seems the datasource and delegate need to be set at first place but the app failed before i can set them in my viewController.
Here is the error :
![capture d ecran 2015-05-13 a 17 08 26](https://cloud.githubusercontent.com/assets/3594599/7613779/03ee31d2-f993-11e4-97fb-fbd50605b586.png)

Could you help me with that ?

Thanks in advance

**Comment by inPhilly** [comment] 2015-05-13 15:47
Same issue - what timing! I agree that the issue may be related to the setting of the MXSegmentedPagerDataSource and MXSegmentedPagerDelegate. I hook up the MXSegmentedPager to a view controller's view in Storyboard and make the MXSegmentedPagerDelegate and MXSegmentedPagerDataSource IBOutlets and connect them to the view  controller in storyboard, but in the reloadData method they are still not registering.

**Comment by inPhilly** [comment] 2015-05-13 16:17
Actually, when I hook it up in Storyboard and make the viewController's view, itself, the MXSegmentedPager, it works fine. But when I add a view as a subview to the main view, and add constraints on that view, and hook that view up to MXSegmentedPager, I see this issue, even with the MXSegmentedPagerDataSource and MXSegmentedPagerDelegate hooked up as explained above.

**Comment by maxep** [comment] 2015-05-13 17:04
Thanks @florentdouine and @mommyme for the report. I will have a look asap!
Yes, it should work by using the segmented-pager as the controller's view as I do in the MXExampleViewController, but I didn't test it as a subview...

**Comment by inPhilly** [comment] 2015-05-13 18:07
Thanks @maxep ! I actually hadn't updated my code to include your latest changes. I just did that, and now even using the segmented-pager as the controller's view yields the error above. The difference between this and your MXExampleViewController in storyboard is that you don't have the the segmented-pager hooked up via IBOutlet in storyboard.

**Comment by inPhilly** [comment] 2015-05-13 18:19
Also to clarify, I'm not hooking up the MXPageController, but the MXSegmentedPager.

**Comment by maxep** [comment] 2015-05-13 18:40
Well, I set a MXSegmentedPager as a controller's view subview in a storyboard but I dont reproduce the crash. Here is my controller:

``` objective-c
@interface MXTestViewController () <MXSegmentedPagerDelegate, MXSegmentedPagerDataSource, UITableViewDelegate, UITableViewDataSource>
@property (weak, nonatomic) IBOutlet MXSegmentedPager *segmentedPager;

@property (nonatomic, strong) UITableView       * tableView;
@property (nonatomic, strong) UIWebView         * webView;
@property (nonatomic, strong) UITextView        * textView;

@end

@implementation MXTestViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view.

    self.segmentedPager.delegate = self;
    self.segmentedPager.dataSource = self;
}

...
```

Is that how you set your controller ?

**Comment by florentdouine** [comment] 2015-05-13 21:43
Yes, i did exactly the same configuration with controller extending UIViewController.
I'm using the last iOS SDK with AutoLayout and Sized classes. 

That's weird...

**Comment by inPhilly** [comment] 2015-05-14 04:25
I did get it to work without crashing for the new version with your setup as above. But (and this may be a new issue) MXSegmentedPager does not resize properly on rotation on an iPad when it is a subview of the main view and is constrained to the four sides of its superview.

**Comment by inPhilly** [comment] 2015-05-14 05:14
I noticed that there are no constraints set on the segmentedControl. Trying to figure out where constraints have and have not been set..

**Comment by maxep** [comment] 2015-05-14 07:56
@mommyme yes that might be another issue. But it works for me when I add constraints, it properly lays out the segmented-control and pages on rotation.

@florentdouine Do you use the latest code ? And do you properly set the data source methods, I do have this crash when I set:

``` objective-c
- (NSInteger)numberOfPagesInSegmentedPager:(MXSegmentedPager *)segmentedPager {
    return 0;
}
```

**Comment by florentdouine** [comment] 2015-05-14 09:53
I'll try again tomorrow and get to you two with the results... 
Thanks for your answers anyway ;)

**Comment by inPhilly** [comment] 2015-05-15 00:23
@maxep does it work with constraints in iPad? If so, is there a way that I can get a hold of your sample project?

**Comment by florentdouine** [comment] 2015-05-15 10:49
@maxep Unfortunately i still get the error when i use your configuration. Here is my code 

``` objective-c
#import "GMHomeViewController.h"

@interface GMHomeViewController () <MXSegmentedPagerDelegate, MXSegmentedPagerDataSource, UITableViewDelegate, UITableViewDataSource>
@property (weak, nonatomic) IBOutlet MXSegmentedPager *segmentedPager;

@property (nonatomic, strong) UITableView       * tableView;
@property (nonatomic, strong) UIWebView         * webView;
@property (nonatomic, strong) UITextView        * textView;

@end

@implementation GMHomeViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view.

    self.segmentedPager.delegate = self;
    self.segmentedPager.dataSource = self;
}


#pragma mark MXSegmentedDataSource

- (UIView*) segmentedPager:(MXSegmentedPager*)segmentedPager viewForPageAtIndex:(NSInteger)index{
    return index==0?_tableView:_webView;
}

- (NSInteger) numberOfPagesInSegmentedPager:(MXSegmentedPager *)segmentedPager{
    return 2;
}
```

But the application crash before access the datasource functions above...

I worked around by creating a GMSegmentedPager class that extends MXSegmentedPager and set datasource and delegate in the init function:

``` objective-c
- (id) initWithCoder:(NSCoder *)aDecoder{
```

**Comment by maxep** [comment] 2015-05-15 11:48
As you said, its weird...
I don't see initialization of your _tableView and _webView, but if it crashes before accessing datasource, thats shouldn't be it. If by any chance you have a sample project that reproduce the issue, I could have a look!

Do you use the standard class or the parallax category ?

**Comment by inPhilly** [comment] 2015-05-15 16:37
@florentdouine Some random thoughts that probably won't help but I thought I'd try...

Did you comment out the method: - (MXSegmentedPager *)segmentedPager

I have the segmentedPager property set as strong - would that make a difference?

What does your viewWillLayoutSubviews method look like?

**Comment by inPhilly** [comment] 2015-05-15 18:29
@florentdouine Also, if there is some reason the loading of MXSegmentedPager would be inhibited as the app is starting up, that could cause this problem.

**Comment by maxep** [comment] 2015-05-20 10:12
Hi @florentdouine 
I will close this issue since I can't reproduce. If you have the same problem using the latest code or any further information about it, please reopen!

PS: joli portfolio :)

**Closed as completed by maxep** 2015-05-20 10:13 UTC
Labels: bug

**Comment by florentdouine** [comment] 2015-05-20 10:28
I just a find a solution for my problem that could help you @mommyme 

``` objective-c
- (void)viewWillLayoutSubviews {
    self.segmentedPager.frame = (CGRect){
        .origin = CGPointZero,
        .size   = self.view.frame.size
    };

    [super viewWillLayoutSubviews];

}
```

It solved the error of NSRangeException.

Hope It helps :

PS: Merci @maxep, petit apparté en français c'est plus pratique :) Bon courage pour maintenir cet outil. Il est très pratique en tout cas !
